### ISSUE TITLE
Excavator is not running

### ISSUE THREAD

**Issue by rinkal26783** [Sniffdog/Sniffdogminer#114]
I have downloaded excavator from nicehash and placed it in bin folder but its not detecting excavator.
It's still using ccminer for neoscrypt.

**Comment by Sniffdog** [comment]
yes goto Miners folder and remove the # in front of neoscrypt algo in ExcavatorNvidianeo.ps1

![screenshot 47 _li](https://user-images.githubusercontent.com/30452757/35704481-f013ef32-075c-11e8-84c7-fc2fb5bfc4ab.jpg)

then Excavator will download to bin folder 

![screenshot 48 _li](https://user-images.githubusercontent.com/30452757/35704629-5e38bd94-075d-11e8-9910-ea5957bc5c25.jpg)

You will now have to move(copy) the files and paste them one folder back Bin\Excavator

The reason as to why is because of EULA distribution (I'm not allowed to distribute) so you needed to manually remove # in ExcavatorNvidianeo.ps1 then as a confirmation that you are personally wanting this you had to move into other folder...

Sorry if it's so many steps but has to be done

**Comment by Klein80** [comment]
Its ccminer for Neoscript not fine or what?

**Comment by Sniffdog** [comment]
no problem and yes KlausT Ccminer works fine and is the default miner (some just like to push their rigs a little more)
