### ISSUE TITLE
Miner closes on interval

### ISSUE THREAD

**Issue by robbowz** [Sniffdog/Sniffdogminer#156]
Hi, is it possible so that when the same coin it's currently mining is the most profitable after interval, that it does not restart the miner? Feels like i'm loosing out a bit because of this.
Current "solution" is to up the interval seconds, but then again i feel like i might loose out again if it's too high.

Also, do you happen to know if there is a problem with Skein algorithm and GTX960? When it uses alexis to mine Skein it goes 100% Load to 0% load every second, up and down, it's not a big issue since most my cards are 1070ti and 1080ti but i've just never seen anything like that and have a feeling it might be bad for the card.

Love the script btw, feels like this one have more potential than many other scripts i've tried!

**Comment by Sniffdog** [comment]
probably because im using cuda 8 alexis and it's affecting your card

try opening another miner in miners folder by right clicking on a file and choosing edit... then it's just a matter of removing the # in front of the left algo and then if you don't like using that one just add the # back to the front of the left algo...

If you do this manual operation... you can check out Ccmineralexis.ps1 and by the same process of right clicking on the file and choosing edit... you can see all the algos and scrolling lower to Optimizations..... seeing all the settings.... 

Then you can lower intensities in alexis if you want... skies the limit to this multiminer.... once you get the hang of it... it will be your pal :)

**Comment by robbowz** [comment]
I will try that out, hopefully it won't affect my 1080ti that's stacked next to it too much by changing miner.

Thanks for the fast response, any miners you would suggest to add Skein to instead of cuda 8 alexis?

Also, the first question is there any way to make it stop restarting the miner when it refreshes the interval if the most profitable coin is the same coin?

**Comment by Sniffdog** [comment]
no your 1080ti is extremely tough... your combining a gen 9 with a gen 10 card... you might want to try out Hashsynminer at my git that is ported and you can change all the settings......

What I mean is each card will have it's own separate miners with it's own set of adjustments as I was mentioning above

the con to hashsynminer is that it takes a bit to setup but worth it in the long run

**Comment by robbowz** [comment]
There isn't a way of choosing GPU manually in the coding? So i can exclude the 960 and use that in another program?

**Comment by Sniffdog** [comment]
hashsynminer.... multiple splitting rig... multiple addresses
