### ISSUE TITLE
MultiAlgo works incorrectly (miner STRATUM link is missing pool address)

### ISSUE THREAD

**Issue by CryptoHashMan** [Sniffdog/Sniffdogminer#23]
Hello, 

This looks more like a Powershell variable problem. And same mistake is in all Miner PS1 scripts, connection looks like this for every algo: stratum+tcp://:4533

Looking forward to hear your opinion.

Cheers.

**Comment by Sniffdog** [comment]
yeah it's a pool issue...

**Comment by CryptoHashMan** [comment]
What do you mean pool issue?

**Comment by gobbx** [comment]
It means the algo isn't available on that pool or there are issues with that pool.

**Comment by CryptoHashMan** [comment]
Hey, you are definitely wrong :) I wouldn't raise the problem if there
would be such noob'ish problem. I am mining that algo separately and it
works perfectly but I want to setup algo-switching stuff, and your tool
looks good. I would be happy to know if I am doing something wrong but I am
not altering any of the files shipped in your package - only wallet
address, GPU count and target username (as per guidance)

Could you do some research? As soon as powershell executes the batch for
CCminer (any of those that are in your package) - variable supplies empty
value that causes stratum string to miss actual pool path.

**Comment by Sniffdog** [comment]
ok I will download Sniffdog and run again....

Here we go downloading......

**Comment by Sniffdog** [comment]
new main api... removed cryptonator

**Comment by cryptomandingus** [comment]
So I found out what the issue was and there was an issue

he set his location to Europe and as a result it does not find stratum links, the same issue occurs with nemos miner when it tries to find the API. 

Therefore, being European myself in snifferdog.bat how would I set my location to Europe. Would I set to just "EU" rather than "europe" or is it not possible as this is set up only for US users?

Thanks in advance

**Comment by Sniffdog** [comment]
the default setting is in US in the startsniffin.bat in location

powershell -version 5.0 -noexit -executionpolicy bypass -windowstyle maximized -command "&.\SniffDog.ps1 -Username Tyredas -Workername Beeboop -Currency USD -Passwordcurrency BTC -interval 90 -Delay 1 -Wallet 1AMQg6m9GPDN9HGuC3wJGpSuiZr1XQXjxi -Location US -PoolName zpool,hash,MPH,ahashpool -Type nvidia,cpu -Algorithm phi,hsr,xevan,tribus,c11,lbry,skein,equihash,groestl,sib,bitcore,blakecoin,Nist5,MyriadGroestl,Lyra2RE2,neoscrypt,skunk,keccak,x11evo,veltor,blake2s,hmq1725,x17,lyra2z,timetravel,polytimos -Donate 5

**Comment by cryptomandingus** [comment]
No I know that, I was saying that when you change the location to EU it causes it to not find the stratum links

**Comment by Sniffdog** [comment]
yes cause you are suppose to use europe for location

**Comment by cryptomandingus** [comment]
let me explain this to you more simply (sorry if this sounds condescending):

Here are the steps I followed that DID NOT WORK
Go to snifferdog.bat
Change location from US to europe#
Run snifferdog.bat
It starts benchmarking
it attempts to run ccminer
it cannot find a stratum link to connect to as one does not exist 
it just says "couldn't connect to stratrum trying again in 30 seconds"


Now what I did to fix this was:
Start snifferdog miner and keep the location as US
run .bat 
everything runs fine

This issue is that if I set the location to "europe" the miner does not work, you have not put in stratum links for an EU connection or something link that.

**Comment by Sniffdog** [comment]
yes because you leave everything "as is" until the benching is done... then change to europe

**Comment by cryptomandingus** [comment]
ohhh I see, well now that it is done bench-marking I can test that.

yep you were right, that fixed the issue. 

Thanks a lot :)

**Comment by Sniffdog** [comment]
No problem I'm hoping in the near future we will fix that issue so you can successfully mining in europe :)

**Comment by CryptoHashMan** [comment]
Thanks Guys, and I am happy that I was not the only one who experienced this, otherwise it's difficult to prove. I will try out your solutions and will update if any other issues. I appreciate your efforts.

Cheers!
