### ISSUE TITLE
When and best way to update to most recent version

### ISSUE THREAD

**Issue by Slickmojo** [Sniffdog/Sniffdogminer#44]
Quick request for advice...when should you update to the newest Sniffdogminer version, and what is the best way to accomplish this?  It is probably dependent upon what pool/setup you are mining with, but is there a general rule with version numbers etc?  For specifics, I have V2.8, a 1080ti, and use ahashpool.  Thanks.

**Comment by Sniffdog** [comment]
I just put out a new one Slickmojo so here is what I would do...

1) Download 3.2

2) Run and let miners unpack

3) Goto your old Sniffdog and copy/paste Stats to new Sniffdog 3.2

4) Goto your old Sniffdog and copy/paste startsniffin.bat to your new Sniffdog 3.2

That's about it... this year I will try to get Sniffdog updater

**Comment by Slickmojo** [comment]
Nice, I am on it...you are awesome!

**Comment by birdsum** [comment]
Dear sir,

Is 3.2 better than 2.8A in ahashpool website?

Thank you

**Comment by Slickmojo** [comment]
Birdsum,

I really cannot answer that as it is kind of an apples/oranges comparison with two separate time periods.  The earning rates were consistent.  I did have a problem getting xevan to benchmark/run, although it has not been one that would run much so I am not that worried by it.  If you are interested in CPU mining it seems to work in 3.2.

Also, just recently I am having problems with ahashpool connecting...  hope it is a short term problem, it has been working really well for me.

Thanks.

**Comment by Sniffdog** [comment]
Yes ahashpool has been working well... most of the time the pool operators are working in the background

I have done many updates with Sniffdog... most of the updates are miner related but one important feature since 2.9 is the removal of cryptonator API for coinbase...

Are you not seeing in 2.8.... keccak algo being out? That's because zpool changed to GHs

Little by little we are adding new updates to get Sniffdog stable so we can get out and enjoy life and not to worry so much about how the rig is performing.

My last trip, I was gone for over a week and Sniffdog never caused a problem

**Comment by birdsum** [comment]
Thanks guys.

I am using 1080Ti. So, I would like to get the best version for supporting my rig.

If 3.2 is better with ahashpool, I will go with it.

Ahashpool does not update sniffdog version on their website.

Anyway I like sniffdog :)

**Comment by Sniffdog** [comment]
Thanks !
