### ISSUE TITLE
Low difficulties

### ISSUE THREAD

**Issue by elf1ua** [Sniffdog/Sniffdogminer#5]
![lowdiff](https://user-images.githubusercontent.com/31589306/30002746-cc1a1a26-90b9-11e7-99ae-1d37f49444dc.jpg)
There is a need to setup diff manually or via hot keys. This is not the first I'm getting continuous low diff warning on 1080TIs and 1060s

**Comment by Sniffdog** [comment]
Yes that is from the pool stratum and not from Sniffdog...

Usually this occurs when stratum diff changes to the next higher diff or when stratum server is stuck on diff and doesn't from the pool.

Honestly, Sniffdog does not use diff in it's password phrase due to the auto switching setup.... every algo is different if diff

**Comment by sypher9** [comment]
go to the miners folder, edit the file "" with Powershell. Scroll down the the "Optimization" section, and replace the keccak line with the following:

**Comment by Sniffdog** [comment]
Yes that works to sypher9 :) 

Thanks for your support! 

Pool Operators have been telling me as well that hashing power has grown substantially over the last few years and more developing is needed to increase diff levels (some algos are maxed out already) 

It's a topic to which I let the pool operators work on.... Once again Thank you sypher9!
