### ISSUE TITLE
You think Sniffdog is complicated and big.... Wait till you get a load of SplitSniff

### ISSUE THREAD

**Issue by Sniffdog** [Sniffdog/Sniffdogminer#57]
SplitSniff will solve the problem of mixed rigs and multiple addresses... You better turn off your overclocking and make sure your rig is built correctly for SplitSniff.... Not for the light hearted :)

**Comment by neoplastic** [comment]
Great stuff! Just got a few questions about SplitSniff.

What are the advantages of putting 2 different GPU vendors into a single rig? Or is SplitSniff designed so we can use AMD chipsets with your, pretty great, algo/pool switching?

Are there any specific GPUs we should be using? SniffDogMiner is designed specifically for the 1080 Ti so is SplitSniff weighted to the 1080 Ti and, maybe something like, Vega 56/64?

The AMD chips are often good at dual mining, popular pairs are Eth/Decred. Is there any kind of feature in SplitSniff for this? Like Split-SplitSniff?

Love your work btw, and really good timing since I was about to look into some AMD chipset mining crypto-portfolio diversity.

**Comment by Sniffdog** [comment]
So far SplitSniff is weighted for nvidia cards and with the first release... lets just make sure it runs first haha.... but yes you are seeing what I am doing.... :)

Last two days I have been testing benching... and 6 accounts and integrating multi altcoin wallet accounts

Just gotta finish up EWBF... gotta read up on every miners just to make sure it runs correctly...

**Comment by Sniffdog** [comment]
https://github.com/Sniffdog/Hashsynminer/releases/tag/0.1

working on removing Splitsniff tags from Hashsynminer

**Comment by YagerD** [comment]
Is Hashynminer a better option that sniffdogminer for Nvidia miners?  I am running 3 1070's and have been working with multiple multi algo / multi pool miners to try to find the best setup possible.  Appreciate all your hard work.

**Comment by Sniffdog** [comment]
If your dedicating all three cards to mine then Sniffdog is fine... it's when you have 1080ti,1080,1070,980ti in your rig and you want to have different intensity settings for each one OR maybe you want to mine with different Wallet addresses for different altcoins...
