### ISSUE TITLE
Multiple Algorithms which don't Benchmark or Work 

### ISSUE THREAD

**Issue by pokepud3** [Sniffdog/Sniffdogminer#60]
So before I removed these algorithms rather than report them but attempting to squash any more bugs on here so I took pics of each of the problematic algorithms which i can't benchmark for some reason with. 

Problems are with:
x11evo, poly, and veltor.

https://imgur.com/eybYHKP
https://imgur.com/6b01Yzf
https://imgur.com/dzvQXAo

They all seem to not register the mining pool address.

**Comment by Sniffdog** [comment]
Yeah... it happens when zpool is down.... not the algo's fault

**Comment by Sniffdog** [comment]
very strange I have not changed the settings since the beginning and zpool still has these algo's

I was also for the past week downloading and re-downloading  sniffdog and all algo's passed 

Maybe just try again later on those algo's... if not Sniffdog will stop using those algo's after three trys
