### ISSUE TITLE
TerminatingError(New-Object)

### ISSUE THREAD

**Issue by cappucup** [Sniffdog/Sniffdogminer#65]
when I run the program for 24 hrs.(some time more). my computer is stuck so I have to restart and when I see the logs file, every time it will have this message "PS>TerminatingError(New-Object): "Exception calling ".ctor" with "2" argument(s): "No connection could be made because the target machine actively refused it 127.0.0.1:4068"". So how can I fix it? Thanks

**Comment by Sniffdog** [comment]
Something is interfering with you remote connection attempts... probably the 4068 default port which ccminer indicated by 127.0.0.1:4068...

For example in Tpruvot README.... -b, --api-bind=port   IP:port for the miner API (default: 127.0.0.1:4068), 0 disabled

In the last few days I have seen this pop up on my rigs too... my rigs have never seen so many issues since the new year and this problem @cappucup... is a new one...

My rigs ran with only a reboot every 24 hours... and ran for months without issues.... so I'm leaning towards what has been happening at the pools OR the new Tpruvot ccminer 2.2.4 (one of the most cleanest ccminers I know of)
