### ISSUE TITLE
Will sniffdog work as well with 1070 Tis?

### ISSUE THREAD

**Issue by romajc84** [Sniffdog/Sniffdogminer#96]
Love this miner. Works way better than others I've tried with my 7x 1080 Tis. Is sniffdog optimized for 1080 Tis?  Wondering how and why. And what differences I can expect if I build a 1070 Ti or mixed rig.

**Comment by Sniffdog** [comment]
you will find nothing will change... I test this software for 1070,1080,and 1080ti

You only have to try it out for yourself to see if this is worthy enough for you

**Comment by romajc84** [comment]
I was just wondering what makes miners differ in performance.

Do difficulty levels automatically get set or is it manually set in the code?

**Comment by Sniffdog** [comment]
SniffDog is at a default setting but if you go into miners folder you can adjust settings accordingly....

Honestly... I'm not sure what you are looking for since there are other miners just as equally good....

We just try to keep SniffDog updated as best as we can but we don't build your rigs (I hope you understand)
